# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='events/photos')),
                ('name', models.CharField(max_length=140)),
                ('location', models.CharField(max_length=140)),
                ('date_time', models.DateTimeField()),
                ('description', models.TextField()),
            ],
        ),
    ]
