# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('origin', models.CharField(max_length=140)),
                ('destination', models.CharField(max_length=140)),
                ('depart_date', models.DateTimeField()),
                ('return_date', models.DateTimeField(blank=True)),
            ],
        ),
    ]
