# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='depart_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='travel',
            name='return_date',
            field=models.DateField(blank=True),
        ),
    ]
